### ISSUE TITLE
LAN incompatibility

### ISSUE THREAD

**Issue by ClockwerkKaiser** [Bletch1971/PixelmonInformation#1]
**Describe the bug**
I recently included this mod in my Pixelmon modpack, and have received reports that players cannot connect to each other when playing over LAN. This issues they are seeing is "fatally missing registry entries". Upon testing, the missing entries all seem to be related to pixelmon drops in JEI.

Here is a pastebin: [https://pastebin.com/1cH7cAzV](https://pastebin.com/1cH7cAzV)

I do understand that this is a client-side only mod. I have advised players who host LAN to disable the mod for the time being. 

 - Pixelmon Information Version: 0.2.7
 - Pixelmon Version: 7.0.1
 - JEI Version: 4.14.4.264
 - Waila Version: HWYLA 1.8.26-B41_1.12.2

**Comment by Bletch1971** [comment]
@ClockwerkKaiser ,

Would it be possible to get the name of your mod pack? I would like to try it out myself.

I run my own dedicated server that I connect to via my LAN and I do not have any problems at all. I do not run it with any other mods, other than the Pixelmon mod and some sidemods. I also test it on single player worlds as well.

You are using a newer version of JEI than I built against, and I am wondering if something has changed than I should test for. 

For those experiencing the problems, does disabling the pokemon drops option in the config settings, fix the problem?

**Comment by Bletch1971** [comment]
@ClockwerkKaiser 

I am trying to fix the problem but I need more information. I have downloaded your mod pack (nice) and tried to perform a LAN host to get the crash.

1. Can you try to reproduce it?
2. Do you know what steps to reproduce it?

This is what I did to try and reproduce:
1. Downloaded your mod pack through twitch client.
2. Started the mod pack via the twitch client.
3. Clicked the play button on the Minecraft launcher.
4. Started a new single player world - Survival, enable cheats. Other options were left untouched.
5. Selected my pokemon and click start button.
6. Hit Escape in game and clicked 'Open to LAN' button from the menu screen.
7. Set to survival and enable cheats, click 'Start LAN World' button.
8. Chat now tells me the port number and everything is good.

Any additional information would be helpful.
Thanks

**Comment by ClockwerkKaiser** [comment]
Starting the LAN host isn't the issue. That works fine. Connecting to a LAN host is where the issue lies.

Upon trying to connect to a LAN world, the connecting client get the error and is unable to play. 

Here is a video of what happens: [https://streamable.com/sudry](https://streamable.com/sudry)

After some more testing, disabling the Pokemon drops option works. However, that is quite literally my favorite part of your mod.

**Comment by Bletch1971** [comment]
@ClockwerkKaiser 
Thank you for the information. I will see what I can do to fix the issue,

**Comment by Bletch1971** [comment]
@ClockwerkKaiser 
I have a new version (0.2.8) ready with a fix. I am able to connect via LAN now, but would like you to confirm the fix.
Would you be willing to test this for me? If so, how do you want me to send to you?

**Comment by Bletch1971** [comment]
Version (0.2.8) pushed to the beta section for testing.

**Comment by Bletch1971** [comment]
Confirm fixed in version 0.2.8
