### ISSUE TITLE
One Probe Formatting Badly

### ISSUE THREAD

**Issue by Dragnier** [Bletch1971/PixelmonInformation#11]
When your information displays via The One Probe mod, it is formatted horribly. It doesn't wrap until it hits the edge of the screen causing the tooltip to be off the left of the screen. It makes the information hard to read.

**Comment by Bletch1971** [comment]
I have been able to reproduce using a smaller screen resolution.
This will be fixed in the next version - 0.3.3.

**Comment by Bletch1971** [comment]
this has been fixed in version 0.3.3.
