### ISSUE TITLE
<ERROR> [PixelmonInformation-1.12.2-7.2.0-0.3.4]

### ISSUE THREAD

**Issue by superon** [Bletch1971/PixelmonInformation#12]
**Describe the bug**
pokémon info is mostly "ERROR"

**To Reproduce**
See error

**Expected behaviour**
See Information

**Screenshots**
[https://hosting.photobucket.com/images/aa271/shakinglikeafool/0/2020-03-29_18.35.36.png]

**Mod Information (please complete the following information):**
https://pastebin.com/61pF6Ukn

mods listed preceded by "-- " are different from client in the case of cci or just serverside (in the case of the others)

**Additional context**
took a while doing this because photobucket insisted i was 906 photos into my 250 photo limit

**Comment by Bletch1971** [comment]
@superon was this version working at any time? Did you have it installed with Pixelmon 7.2.0?
I am wondering if the new version 7.2.2 has changed something.

**Comment by superon** [comment]
idk, updated to this version when updating to latest pixelmon iirc :/

**Comment by superon** [comment]
i think this was because i didn't actually have hwyla installed on the server.. i mean i did just notice is wasn't on and added it and i can now see full info on pokémon.  i have done other fiddles as well but it makes sense that this would be the cause so i'll slap the close on this Issue :)
