### ISSUE TITLE
Pixelmon crashes when i enter the pc

### ISSUE THREAD

**Issue by NoirBat** [Bletch1971/PixelmonInformation#15]
I installed the latest pixelmon reforged version and it always crashes whenever i enter the pc even if i use the /pc command.
I have to say im not playing on an actual pc but on an android phone with mcinabox.
I have the forge version 1.12.2 2847 
Pixelmon reforged 8.0.2

I will try to put the crash report below.
[crash-2020-07-14_05.11.12-client.txt](https://github.com/Bletch1971/PixelmonInformation/files/4921928/crash-2020-07-14_05.11.12-client.txt)

**Comment by Bletch1971** [comment]
@NoirBat this error is not related to Pixelmon Information, but Pixelmon.
You may want to log the issue with the Pixelmon devs.
