### ISSUE TITLE
8.1.2 Update Request

### ISSUE THREAD

**Issue by LatiusAuro** [Bletch1971/PixelmonInformation#16]
There are items in the recent updates which don't have any details about them, especially the new TMs and TRs, Also, it would be a good idea if there was a page in JEI dedicated to the Curry Dex, showing what each key ingredient makes when used as the Key Ingredient.

**Comment by Bletch1971** [comment]
Let me take a look and see what I can do.

**Comment by Bletch1971** [comment]
Until they are updated on the wiki, I am unable to provide the details in the mod.
