### ISSUE TITLE
The One Probe - Show When Sneaking option not working correctly

### ISSUE THREAD

**Issue by MGVice** [Bletch1971/PixelmonInformation#17]
**Describe the bug**
When The One Probe - Show When Sneaking option is turned on the extra information is not shown when sneaking. However when the option is turned off all the information is shown correctly all the time, as expected (see screenshots)

**To Reproduce**
1. Be sure to have just The One Probe, Optifine, Pixelmon and Pixelmon Information installed
2. Be sure to have The One Probe - Show When Sneaking option turned on
3. Start singleplayer game and look at pokemon while sneaking
4. See that pokemon extended information does not show up 
5. Change The One Probe - Show When Sneaking off
6. look at pokemon normally and see that the information is shown correctly

**Expected behavior**
The same information that is shown when 'Show When Sneaking' is off should be shown when the option is turned on but only when sneaking (right now it's not at all when the option is enabled, sneak or not)

**Screenshots**
option enabled
![2020-10-14_00 15 03](https://user-images.githubusercontent.com/52075112/95947220-c330e280-0db3-11eb-9a87-c56c63701feb.png)

The One Probe while sneaking
![2020-10-14_00 15 21](https://user-images.githubusercontent.com/52075112/95947252-d2179500-0db3-11eb-9064-dd5d76fce825.png)

option disabled
![2020-10-14_00 15 00](https://user-images.githubusercontent.com/52075112/95947271-d8a60c80-0db3-11eb-93e4-df4caeeb03fa.png)

The One Probe looking at pokemon
![2020-10-14_00 14 44](https://user-images.githubusercontent.com/52075112/95947302-e9ef1900-0db3-11eb-9651-a1e2cd4616ce.png)

**Mod Information (please complete the following information):**
 - Pixelmon Information Version: 0.3.7
 - Pixelmon Version: 8.1.2
 - The One Probe Version: 1.4.28
 - Optifine Version: 1.12.2_HD_U_F5

**Additional context**
This mod is under-rated keep up the good work!!!

**Comment by Bletch1971** [comment]
Thank you for the feedback, glad someone likes it 👍 

As for the sneak issue, there are options that TOP set using it's own book. I do not remember the three options, but one of them may be needed to turn on while sneaking.

I will check out the code and report back.

**Comment by Bletch1971** [comment]
I just checked the code logic and found this

if (ModConfig.top.useSneaking == true && ProbeMode == NORMAL) {
	// do not show the information in TOP, just return empty
}

I cannot for the life of me remember why I added this check. I do not use TOP, but I think it had something to do with the TOP settings.

Maybe play around with the three TOP settings via it's own book and see if they are shown when you change it.

**Comment by MGVice** [comment]
Will do. Also completely forgot I actually installed Vivecraft-NOVR or whatever it was called which pretty much just installs optifine into the minecraft jar file (not that i think this would break your mod just something to keep in mind). I'll take a look thanks!
