### ISSUE TITLE
Implement Potion recipes via brewing stand

### ISSUE THREAD

**Issue by nicholasrobertm** [Bletch1971/PixelmonInformation#18]
**Is your feature request related to a problem? Please describe.**
Potion crafting recipes don't show the recipe

**Describe the solution you'd like**
https://pixelmonmod.com/wiki/Potion
The potions use brewing stands for their recipes, should be straightforward to implement them as regular brewing stand recipes

**Comment by Bletch1971** [comment]
JEI should include the brewing stand recipes by default. Are you not able to see the new Pokemon Brews in JEI already?

Maybe the pixelmon team did not add them to the normal brewing stand recipes list.

Do you use a vanilla brewing stand, or does pixelmon add it's own?

**Comment by nicholasrobertm** [comment]
Heres a picture of what it currently looks like in JEI.
![image](https://user-images.githubusercontent.com/3313264/96661073-da6e5380-1310-11eb-8c52-56b002d2a4d4.png)

Heres a picture of how the pixelmon website says to craft it, it uses the normal brewing stand.
![image](https://user-images.githubusercontent.com/3313264/96661146-02f64d80-1311-11eb-9ada-956b1e5e7881.png)

https://pixelmonmod.com/wiki/Potion

It could be that they're not adding them in the proper way or something like that? Pixelmon not being open source makes it hard to find this out obviously.

**Comment by Bletch1971** [comment]
Can you check a vanilla potion for me and see if JEI shows the brewing stand details for a vanilla potion?

**Comment by nicholasrobertm** [comment]
![image](https://user-images.githubusercontent.com/3313264/96674865-4790e180-132f-11eb-9c70-58eebf87f8b1.png)
Looks like it does! I scrolled through and the pixelmon potions aren't in there just fyi

**Comment by Bletch1971** [comment]
thanks for checking for me. I will try and get them added to JEI.

**Comment by nicholasrobertm** [comment]
Appreciate it!

**Comment by nicholasrobertm** [comment]
also to save you a second, here is the pixelmon page with all their brewing recipes:
https://pixelmonmod.com/wiki/Brewing_Recipes

**Comment by Bletch1971** [comment]
that is awesome, thanks for the link.

**Comment by Bletch1971** [comment]
Sorry for the delay, but have finally been able to figure it all out and add the Potions to JEI.
You need to use Pixelmon 8.2.0 or later and Pixelmon Information 0.3.9.
