### ISSUE TITLE
Int32 max on RF display

### ISSUE THREAD

**Issue by Emeraldspiders** [Bletch1971/PixelmonInformation#19]
Description
     Numbers for RF (potentially others) are capped at max int (2.147 bil), my draconic evolution power core cant show its actual 
     amount, and instead displays 2.1GRF (gigaRF, giga = billion)

Preproduction:
     Create a t4-t7 energy core (first pic, center), fill with more than 2.147 billion RF, check the energy pylons, check the core stabilizers(second pic, top left), energy values dont match actual

What should happen
     TOP should show the actual amount of power in the system

**Screenshots**
![image](https://user-images.githubusercontent.com/37520930/113108694-7fdffa00-91c2-11eb-9cdc-0cc93205be00.png)
![image](https://user-images.githubusercontent.com/37520930/113108748-8bcbbc00-91c2-11eb-99ad-02070c049082.png)

**Mod Information (please complete the following information):**
     -TOB version 1.12, 1.4.28

**Comment by Bletch1971** [comment]
This has nothing to do with my mod - this is a TOP issue.
