### ISSUE TITLE
Request: Mod Update to 8.2.0

### ISSUE THREAD

**Issue by marcobsidian** [Bletch1971/PixelmonInformation#20]
Hiya, I wanted to ask if PixelmonInformations is going to be updated to 8.2.0 or if 8.0.0 compatibility was the last update for the Mod
I think the mod is an amazing tool and super useful but 8.2.0 broke the Tabs "Pokemon Drops" and "Boss Drops" completely. Pokemarts kinda work, but I assume the used NBT Data on the new TMs and TRs messes it up a bit. Looks mostly fine when you look at the Mart Tab via "All Recipes", but when you click the item in JEI for the Recipe it has a bit of a visual bug.

An Update to the Mod would be super cool, mainly so Boss Drops and Pokemon Drops work again :)

**Comment by marcobsidian** [comment]
So... will the mod even get updated to 8.2.0?

Not meaning as you should rush it, but getting a heads up if it will happen in the first place would be great :)

**Comment by Bletch1971** [comment]
I am not going to promise anything.
I need time to figure out what has changed and how to get the information from the mod.

I do a lot of funky shit to make my mod work now, as most of the information is not available publically.
There is a lot of things I am just not able to add to the mod that I would have liked due to the way the Pixelmon mod stores and exposes the information.

**Comment by marcobsidian** [comment]
Alright thanks for the response :D

Take all the time you need, Quality > Rushing it done

**Comment by Bletch1971** [comment]
New version of the mod is now available 0.3.8 for Pixelmon 8.2.0.
This version will fix the boss drops.

Take a look and let me know.

**Comment by marcobsidian** [comment]
Everything works now :D The only issue i found is that somehow now JustEnoughRessources Chest Loot isnt shown at all anymore, even at default config. So basically no chest loot at all shown now

**Comment by marcobsidian** [comment]
tried clicking on the master ball in jei and all it showed me is pokeloot and boss drops. no end cities or similar stuff...

or is that just an issue on my end?

**Comment by marcobsidian** [comment]
update: overall jer is gone now, none of the jer tabs at all are shown

**Comment by marcobsidian** [comment]
nevermind, it was an issue with another mod that I downloaded recently and just discovered for the first time. removed the mod and JER is back.

everything seems to work as intended with the mod :) thanks for the quick update, really appreciated
