### ISSUE TITLE
Update to latest Pixelmon version

### ISSUE THREAD

**Issue by beerik94** [Bletch1971/PixelmonInformation#23]
They released a new pixelmon version for minecraft 1.16.5
Would be amazing if you are able to update this to work with that version.

**Comment by Bletch1971** [comment]
Thanks you the update. Will take a look and see what I can do.

**Comment by beerik94** [comment]
Yeah I had a look as well already and all the mods have changed. TOP, HWYLA, etc. all have completely different APIs now. And there is the problem of minecraft 1.16.5 being really different from 1.12.2
Felt to me like it will result in almost a compleet rewrite of how stuff is rendered.

**Comment by Bletch1971** [comment]
Nothing like starting fresh :(
With any luck it might be easier this time around.

**Comment by Bletch1971** [comment]
I have released the first version of the mod with 1.16.5 that includes Tooltips, WAILA and TOP.
Am working on JEI integration for the next version.
