### ISSUE TITLE
Can you add - The one probe support for 1.12.2 and on or Add a way to extend Hywla view distance

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Bletch1971/PixelmonInformation#3]
**Is your feature request related to a problem? Please describe.**

No 

**Describe the solution you'd like**

Hywla won't extend the range of wailia view distance past immediate block vicinity. Alos having both Waila and The One Probe is annoying.

**Describe alternatives you've considered**

Are any alternatives available? Can you make a mod that extends view distance for pixelmon wailia?

**Additional context**

No

**Comment by Bletch1971** [comment]
I will look into the one probe. If it has an api then it should not be too hard to do. 

I do agree with your issue with waila and it’s derivitives. The distance should be configurable. 

Let me see what I can do. Thanks for the suggestion.

**Comment by P3rf3ctXZer0** [comment]
Thank you very much for your time - I look forward to further updates :D

**Comment by Bletch1971** [comment]
The one probe has been implemented into version 0.3.0.
I have also added an option to the config to only show the Waila and The One Probe information when sneaking.

**Comment by P3rf3ctXZer0** [comment]
Great addition :D thanks for helping me and making my life easier.
