### ISSUE TITLE
The One Probe - Does not show Information.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Bletch1971/PixelmonInformation#4]
**Describe the bug**

Well I figured it would play like wailia but unfortunately it is not. Even when hovering over an entity it is not showing extended information.

**To Reproduce**

**Expected behavior**

When hovering see information.

**Screenshots**

![2019-02-24 11_35_46-downloads](https://user-images.githubusercontent.com/10351221/53302848-9d467b00-3828-11e9-9df0-5c8579e515d7.jpg)

**Mod Information (please complete the following information):**
 - Pixelmon Information Version: [e.g. 0.3.0]
 - Pixelmon Version: [e.g. 7.0.3]
 - JEI Version: 
 - Waila Version:
 - TheOneProbe: [1.12-1.4.28] 

**Additional context**

**Comment by Bletch1971** [comment]
This is not a problem with my mod. You need to change the settings of The One Probe to always show the information. There are 3 settings and they are changed by right-clicking The One Probe information page item that you get in your inventory.

Change that to the first option, Show without the one probe.

**Comment by P3rf3ctXZer0** [comment]
I will try that I had more screenshots showing I adjusted one probe.

**Comment by Bletch1971** [comment]
I have not used The One Probe much before, only in certain mod packs.
1. I did not find it as easy to setup and Waila.
2. I found the range to be about the same as Waila, unless I missed a config setting.
3. I am not a fan of the output, but that could be I am just used to Waila.
4. The use of the probe items/helmets, while a good addition, can be confusing with the settings.

**Comment by P3rf3ctXZer0** [comment]
Understood.

**Comment by Bletch1971** [comment]
Thanks for the feedback.
That is another thing, The One Probe is both a server and client side mod because of the probe items and helmets.
Waila can be server and client, or just client.
