### ISSUE TITLE
"Caught option" shows Error in 7.0.4 Pixelmon when using TOP and Hwyla

### ISSUE THREAD

**Issue by luigigiannella** [Bletch1971/PixelmonInformation#6]
![2019-03-21_21 19 17](https://user-images.githubusercontent.com/12875555/54794741-685af780-4c1f-11e9-9ab6-710353c246e1.png)

It working in the previous version of Pixelmon (7.0.3)

**Comment by Bletch1971** [comment]
thanks for the update. I will take a look and see what I can do.

Can you try something for me? Open your Pokedex (you need to press a key), close the pokedex and then see if the error is still there?

**Comment by luigigiannella** [comment]
Error is still there

**Comment by Bletch1971** [comment]
This has been fixed in v0.3.1. Have tested in 7.0.0 -> 7.0.5.
