### ISSUE TITLE
Update to Pixelmon Reforged 7.1.1

### ISSUE THREAD

**Issue by PixelmonPRO** [Bletch1971/PixelmonInformation#9]
**Describe the bug**
When hovering over a pokemon shows an ERROR, and FPS drop.

**To Reproduce**
1. Update to 7.1.0 / 7.1.1
2. Click to R
3. Hover over Pokemon
4. See ERROR, and FPS drop.

**Screenshots**
https://i.imgur.com/eIs4foJ.jpg

**Mod Information (please complete the following information):**
 - Pixelmon Information Version: 0.3.1
 - Pixelmon Version: 7.1.0 / 7.1.1
 - JEI Version: none
 - Waila Version: Wawla-1.12.2-2.5.273
- Forge: 2838

**Additional context**
- Log error: https://gist.github.com/PixelmonPRO/19c40d3ae5a8ed3fef17c8a8f1d8e322
- WailaErrorOutput: https://gist.github.com/PixelmonPRO/f4969b347335ab72c08963f6349c301b

**Comment by Bletch1971** [comment]
I am wondering if it is because on WAWLA? When I use WAILA, I use HWYLA (1.8.26-B41_1.12.2).

I have put out a new version (0.3.2) and I did create one specifically for 7.1.0 version (and higher) of the pixelmon mod. When I did my testing I was able to see ALL the details in WAILA.

I will download WAWLA and see if that might be the cause of the problem.

Also, are you running single player or on a server?
If on a server, do you have it installed on the server - this mod is client side only?

**Comment by PixelmonPRO** [comment]
> I am wondering if it is because on WAWLA? When I use WAILA, I use HWYLA (1.8.26-B41_1.12.2).
> 
> I have put out a new version (0.3.2) and I did create one specifically for 7.1.0 version (and higher) of the pixelmon mod. When I did my testing I was able to see ALL the details in WAILA.
> 
> I will download WAWLA and see if that might be the cause of the problem.
> 
> Also, are you running single player or on a server?
> If on a server, do you have it installed on the server - this mod is client side only?

I apologize for the false information, I got confused in the names of the mods. I use:
- **Forge 2847**
- **Pixelmon 7.1.1**
- **Hwyla-1.8.26-B41_1.12.2**
- **Wawla-1.12.2-2.5.273**
- **PixelmonInformation-1.12.2-7.1.0-0.3.2** (earlier PixelmonInformation-1.12.2-7.0.0-0.3.1)

There is an error only in the multiplayer game, in a single-player game no errors were noticed.
Hwyla and Pixelmon-Informations not instaled on server (previously displaying information worked well, without these mods on the serverside).

**Comment by Bletch1971** [comment]
I did not try testing against a server. Now that I know you have the error only when running server, not single player, I will try to reproduce and fix if possible.

**Comment by Bletch1971** [comment]
Sorry for the late response :(

I have tested all versions of Pixelmon against all versions of my mod and I am unable to reproduce in server.
As my mod is client side only connecting to a server should not make a difference.

Have you upgraded to Pixelmon 7.2.0? If so, do you still have the same issue?

**Comment by Bletch1971** [comment]
Can you please check using the latest version 0.3.3. If the issue persists, can you please log another bug.
